%\VignetteIndexEntry{DAPAR One Page Introduction}
%\VignetteDepends{}
%\VignetteKeywords{Quantitative proteomics analysis}
%\VignettePackage{DAPAR}
\documentclass[12pt,a4paper]{article}

\textwidth=6.2in
\textheight=8.5in
\oddsidemargin=0.2in
\evensidemargin=0.2in
\headheight=0in
\headsep=0in

\begin{document}
%\SweaveOpts{concordance=TRUE}
\title{DAPAR\\(Differential Analysis for Proteomics Abundance with R)}
\author{Samuel Wieczorek, Florence Combes, Thomas Burger}
\date{29 July 2015}
\maketitle


DAPAR (Differential Analysis for Proteomics Analysis with R) is an R package 
for the analysis mass spectrometry-based discovery proteomics quantitative 
dataset. It is built on pre-existing Bioconductor packages devoted to 
proteomics and uses the MSnSet data structure from MSnbase. The package 
contains functions to import data from CSV files (such as those from 
Maxquant), and to export data to Excel files.\\

DAPAR is made to guide the practitioner through the following classical steps 
of a protein-level data analysis: 
\begin{itemize}
    \item \textbf{Descriptive statistics}: Exploration and visualization of 
    your dataset with a detailed overview, which includes the following 
    functionalities:
    Missing Values exploration, 
    heatmap and correlation matrices, 
    boxplots, expectation and variance distribution. 

    \item \textbf{Filtering}: 
    DAPAR allows to filter proteins according to their number of missing 
    values in each condition. 

    \item \textbf{Cross replicate normalisation}, with the following methods: 
    $(i)$ global rescaling (quantiles method, proportion method),
    $(ii)$ median or mean centering (overall or within conditions),
    $(iii)$ mean centering and scaling (overall or within conditions).

    \item \textbf{Missing values imputation}, with the following methods: 
    $(i)$ for random occurences: $k$-nearest-neighbors, Bayesian Principal 
    Component Analysis and Maximum Likelihood Estimation; $(ii)$for left 
    censored missing values: Quantile Regression for Imputation of Left 
    Censored data.
    
    \item \textbf{Differential analysis}, according to a Welch $t$-test or 
    a Limma moderated $t$-test.
    \end{itemize}



\end{document}
