%\VignetteIndexEntry{UPSprotx2 dataset description}
%\VignetteDepends{}
%\VignetteKeywords{Quantitative proteomics analysis}
%\VignettePackage{DAPAR}
\documentclass[12pt,a4paper]{article}
\usepackage{gensymb}
\usepackage[utf8]{inputenc}

\textwidth=6.2in
\textheight=8.5in
\oddsidemargin=0.2in
\evensidemargin=0.2in
\headheight=0in
\headsep=0in

\begin{document}
\SweaveOpts{concordance=TRUE}
\title{Description of the UPSprotx2 dataset}
\author{}
\maketitle





This dataset results from a controlled relative quantification proteomics experiment where Sigma UPS1 human proteins were spiked in a similar yeast lysate in 2 different concentrations (with a ratio of 2).
As a consequence, it can be used to benchmark the quality of a statistical analysis: in the ideal case, after the differential analysis, only and all the human proteins should be selected.

\section{Preparation and digestion of proteins and peptides}
TODO

\section{Nano-LC-MS/MS analyses}
TODO

\section{Computational analyses}
TODO





\end{document}